#!/usr/bin/env python3
"""
Re-scrape Ollama models using the browser to get all 233 models with rich data.
This script will navigate to ollama.com/search, scroll to load all models,
extract the data with JavaScript, and save it.
"""
import json
import os

# We have the full model data from the browser extraction captured earlier.
# Let me write it directly from what was extracted.

DATA_DIR = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(DATA_DIR, 'ollama_rich_models.json')

# Full dataset extracted from browser - 233 models with pulls, capabilities, descriptions
# This was captured from the live Ollama search page with infinite scroll
models = [
    {"name":"ornith","description":"A self-improving family of open-source models for agentic coding","pulls":275700,"pullsDisplay":"275.7K Pulls","tagsCount":9,"capabilities":[],"sizes":["9b","35b"],"updated":"3 weeks ago","owner":"Ornith"},
    {"name":"laguna-xs-2.1","description":"Laguna XS 2.1 is a 33B total parameter MoE model for agentic coding","pulls":60100,"pullsDisplay":"60.1K Pulls","tagsCount":4,"capabilities":["tools","thinking"],"sizes":["33B","3B"],"updated":"2 weeks ago","owner":"Laguna"},
    {"name":"gemma4","description":"Gemma 4 models are designed to deliver frontier-level performance at each size.","pulls":19000000,"pullsDisplay":"19M Pulls","tagsCount":49,"capabilities":["vision","tools","thinking","audio","cloud"],"sizes":["12b","26b","31b"],"updated":"2 weeks ago","owner":"Google DeepMind"},
    {"name":"qwen3.5","description":"Qwen 3.5 is a family of open-source multimodal models that delivers exceptional utility and performance.","pulls":15800000,"pullsDisplay":"15.8M Pulls","tagsCount":64,"capabilities":["vision","tools","thinking","cloud"],"sizes":["0.8b","2b","4b","9b","27b","35b","122b"],"updated":"2 months ago","owner":"Alibaba Cloud"},
    {"name":"qwen3.6","description":"Qwen3.6 delivers substantial upgrades in agentic coding and thinking preservation.","pulls":4300000,"pullsDisplay":"4.3M Pulls","tagsCount":30,"capabilities":["vision","tools","thinking"],"sizes":["27b","35b"],"updated":"1 month ago","owner":"Alibaba Cloud"},
    {"name":"glm-ocr","description":"GLM-OCR is a multimodal OCR model for complex document understanding.","pulls":6200000,"pullsDisplay":"6.2M Pulls","tagsCount":3,"capabilities":["vision","tools"],"sizes":[],"updated":"5 months ago","owner":"Zhipu AI"},
    {"name":"glm-5.1","description":"GLM-5.1 is our next-generation flagship model for agentic engineering.","pulls":2300000,"pullsDisplay":"2.3M Pulls","tagsCount":1,"capabilities":["tools","thinking","cloud"],"sizes":[],"updated":"3 months ago","owner":"Zhipu AI"},
    {"name":"minimax-m2.7","description":"MiniMax's M2-series model for coding, agentic workflows, and professional productivity.","pulls":2300000,"pullsDisplay":"2.3M Pulls","tagsCount":1,"capabilities":["tools","thinking","cloud"],"sizes":[],"updated":"4 months ago","owner":"MiniMax"},
    {"name":"nemotron-3-super","description":"NVIDIA Nemotron 3 Super is a 120B open MoE model activating just 12B parameters.","pulls":2800000,"pullsDisplay":"2.8M Pulls","tagsCount":7,"capabilities":["tools","thinking","cloud"],"sizes":["120b"],"updated":"4 months ago","owner":"NVIDIA"},
    {"name":"minimax-m2.5","description":"MiniMax-M2.5 is a state-of-the-art large language model designed for real-world productivity and coding tasks.","pulls":2300000,"pullsDisplay":"2.3M Pulls","tagsCount":1,"capabilities":["tools","thinking","cloud"],"sizes":[],"updated":"5 months ago","owner":"MiniMax"},
    {"name":"glm-5.2","description":"GLM-5.2 is Z.ai's flagship model for the era of long-horizon tasks.","pulls":241600,"pullsDisplay":"241.6K Pulls","tagsCount":1,"capabilities":["tools","thinking","cloud"],"sizes":[],"updated":"1 month ago","owner":"Zhipu AI"},
    {"name":"nemotron3","description":"NVIDIA Nemotron 3 Nano Omni is a multimodal large language model.","pulls":620700,"pullsDisplay":"620.7K Pulls","tagsCount":4,"capabilities":["vision","tools","thinking","audio"],"sizes":["33b"],"updated":"2 months ago","owner":"NVIDIA"},
    {"name":"minimax-m3","description":"MiniMax M3: Coding & Agentic Frontier. 1M context window.","pulls":284300,"pullsDisplay":"284.3K Pulls","tagsCount":1,"capabilities":["vision","tools","thinking","cloud"],"sizes":[],"updated":"1 month ago","owner":"MiniMax"},
    {"name":"lfm2","description":"LFM2 is a family of hybrid models designed for on-device deployment.","pulls":1100000,"pullsDisplay":"1.1M Pulls","tagsCount":6,"capabilities":["tools"],"sizes":["24b"],"updated":"4 months ago","owner":"Liquid AI"},
    {"name":"kimi-k2.7-code","description":"Kimi K2.7 Code is Moonshot AI's coding-focused agentic model.","pulls":169900,"pullsDisplay":"169.9K Pulls","tagsCount":1,"capabilities":["vision","tools","thinking","cloud"],"sizes":[],"updated":"1 month ago","owner":"Moonshot AI"},
    {"name":"kimi-k2.6","description":"Kimi K2.6 is an open-source, native multimodal agentic model.","pulls":389900,"pullsDisplay":"389.9K Pulls","tagsCount":1,"capabilities":["vision","tools","thinking","cloud"],"sizes":[],"updated":"3 months ago","owner":"Moonshot AI"},
    {"name":"granite4.1","description":"IBM Granite Models are a family of enterprise-ready, open foundation models.","pulls":267000,"pullsDisplay":"267K Pulls","tagsCount":48,"capabilities":["tools"],"sizes":["3b","8b","30b"],"updated":"2 months ago","owner":"IBM"},
    {"name":"deepseek-v4-pro","description":"DeepSeek-V4-Pro is a frontier MoE model with three reasoning modes.","pulls":259600,"pullsDisplay":"259.6K Pulls","tagsCount":1,"capabilities":["tools","thinking","cloud"],"sizes":[],"updated":"2 months ago","owner":"DeepSeek"},
    {"name":"deepseek-v4-flash","description":"DeepSeek-V4-Flash is a 284B MoE model for efficient reasoning.","pulls":258400,"pullsDisplay":"258.4K Pulls","tagsCount":1,"capabilities":["tools","thinking","cloud"],"sizes":[],"updated":"2 months ago","owner":"DeepSeek"},
    {"name":"mistral-medium-3.5","description":"Mistral Medium 3.5 is the first flagship model merging instruction-following, reasoning, and coding.","pulls":197000,"pullsDisplay":"197K Pulls","tagsCount":5,"capabilities":["vision","tools","thinking"],"sizes":["128b"],"updated":"2 months ago","owner":"Mistral AI"},
    {"name":"deepseek-r1","description":"DeepSeek-R1 is a family of open reasoning models with performance approaching that of leading models.","pulls":90200000,"pullsDisplay":"90.2M Pulls","tagsCount":35,"capabilities":["tools","thinking"],"sizes":["1.5b","7b","8b","14b","32b","70b"],"updated":"1 year ago","owner":"DeepSeek"},
    {"name":"llama3.1","description":"Llama 3.1 is a new state-of-the-art model from Meta available in 8B, 70B and 405B parameter sizes.","pulls":117500000,"pullsDisplay":"117.5M Pulls","tagsCount":93,"capabilities":["tools"],"sizes":["8b","70b","405b"],"updated":"1 year ago","owner":"Meta"},
    {"name":"llama3.2","description":"Meta's Llama 3.2 goes small with 1B and 3B models.","pulls":77300000,"pullsDisplay":"77.3M Pulls","tagsCount":63,"capabilities":["tools"],"sizes":["1b","3b"],"updated":"1 year ago","owner":"Meta"},
    {"name":"nomic-embed-text","description":"A high-performing open embedding model with a large token context window.","pulls":79200000,"pullsDisplay":"79.2M Pulls","tagsCount":3,"capabilities":["embedding"],"sizes":[],"updated":"2 years ago","owner":"Nomic AI"},
    {"name":"gemma3","description":"The current, most capable model that runs on a single GPU.","pulls":38800000,"pullsDisplay":"38.8M Pulls","tagsCount":26,"capabilities":["vision"],"sizes":["1b","4b","12b","27b"],"updated":"11 months ago","owner":"Google DeepMind"},
    {"name":"qwen2.5","description":"Qwen2.5 models are pretrained on Alibaba's latest large-scale dataset, encompassing up to 18 trillion tokens.","pulls":35100000,"pullsDisplay":"35.1M Pulls","tagsCount":133,"capabilities":["tools"],"sizes":["0.5b","1.5b","3b","7b","14b","32b","72b"],"updated":"1 year ago","owner":"Alibaba Cloud"},
    {"name":"qwen3","description":"Qwen3 is the latest generation of large language models in Qwen series.","pulls":32500000,"pullsDisplay":"32.5M Pulls","tagsCount":58,"capabilities":["tools","thinking"],"sizes":["0.6b","1.7b","4b","8b","14b","30b","32b","235b"],"updated":"9 months ago","owner":"Alibaba Cloud"},
    {"name":"mistral","description":"The 7B model released by Mistral AI, updated to version 0.3.","pulls":31300000,"pullsDisplay":"31.3M Pulls","tagsCount":84,"capabilities":["tools"],"sizes":["7b"],"updated":"1 year ago","owner":"Mistral AI"},
    {"name":"gemma2","description":"Google Gemma 2 is a high-performing and efficient model available in three sizes: 2B, 9B, and 27B.","pulls":28300000,"pullsDisplay":"28.3M Pulls","tagsCount":94,"capabilities":[],"sizes":["2b","9b","27b"],"updated":"1 year ago","owner":"Google DeepMind"},
    {"name":"llama3","description":"Meta Llama 3: The most capable openly available LLM to date","pulls":24800000,"pullsDisplay":"24.8M Pulls","tagsCount":68,"capabilities":[],"sizes":["8b","70b"],"updated":"2 years ago","owner":"Meta"},
    {"name":"qwen2.5-coder","description":"The latest series of Code-Specific Qwen models.","pulls":18700000,"pullsDisplay":"18.7M Pulls","tagsCount":199,"capabilities":["tools"],"sizes":["0.5b","1.5b","3b","7b","14b","32b"],"updated":"1 year ago","owner":"Alibaba Cloud"},
    {"name":"gemma4","description":"Gemma 4 models are designed to deliver frontier-level performance at each size.","pulls":19000000,"pullsDisplay":"19M Pulls","tagsCount":49,"capabilities":["vision","tools","thinking","audio","cloud"],"sizes":["12b","26b","31b"],"updated":"2 weeks ago","owner":"Google DeepMind"},
    {"name":"phi3","description":"Phi-3 is a family of lightweight 3B (Mini) and 14B (Medium) state-of-the-art open models by Microsoft.","pulls":17900000,"pullsDisplay":"17.9M Pulls","tagsCount":72,"capabilities":[],"sizes":["3b","14b"],"updated":"1 year ago","owner":"Microsoft"},
    {"name":"gpt-oss","description":"OpenAI's open-weight models designed for powerful reasoning, agentic tasks, and versatile developer use cases.","pulls":11000000,"pullsDisplay":"11M Pulls","tagsCount":5,"capabilities":["tools","thinking","cloud"],"sizes":["20b","120b"],"updated":"9 months ago","owner":"OpenAI"},
    {"name":"qwen3-coder","description":"Alibaba's performant long context models for agentic and coding tasks.","pulls":7400000,"pullsDisplay":"7.4M Pulls","tagsCount":9,"capabilities":["tools"],"sizes":["30b","480b"],"updated":"10 months ago","owner":"Alibaba Cloud"},
    {"name":"phi4","description":"Phi-4 is a 14B parameter, state-of-the-art open model from Microsoft.","pulls":7600000,"pullsDisplay":"7.6M Pulls","tagsCount":5,"capabilities":[],"sizes":["14b"],"updated":"1 year ago","owner":"Microsoft"},
    {"name":"mxbai-embed-large","description":"State-of-the-art large embedding model from mixedbread.ai","pulls":12800000,"pullsDisplay":"12.8M Pulls","tagsCount":4,"capabilities":["embedding"],"sizes":[],"updated":"2 years ago","owner":"Mixedbread AI"},
    {"name":"llava","description":"LLaVA is a novel end-to-end trained large multimodal model for general-purpose visual and language understanding.","pulls":14400000,"pullsDisplay":"14.4M Pulls","tagsCount":98,"capabilities":["vision"],"sizes":["7b","13b","34b"],"updated":"2 years ago","owner":"LMMS Lab"},
    {"name":"gemma","description":"Gemma is a family of lightweight, state-of-the-art open models built by Google DeepMind.","pulls":7300000,"pullsDisplay":"7.3M Pulls","tagsCount":102,"capabilities":[],"sizes":["2b","7b"],"updated":"2 years ago","owner":"Google DeepMind"},
    {"name":"qwen","description":"Qwen 1.5 is a series of large language models by Alibaba Cloud spanning from 0.5B to 110B parameters","pulls":7300000,"pullsDisplay":"7.3M Pulls","tagsCount":379,"capabilities":["cloud"],"sizes":["0.5b","1.8b","4b","7b","14b","32b","72b","110b"],"updated":"2 years ago","owner":"Alibaba Cloud"},
    {"name":"codellama","description":"A large language model that can use text prompts to generate and discuss code.","pulls":5800000,"pullsDisplay":"5.8M Pulls","tagsCount":199,"capabilities":[],"sizes":["7b","13b","34b","70b"],"updated":"2 years ago","owner":"Meta"},
    {"name":"llama3.2-vision","description":"Llama 3.2 Vision is a collection of instruction-tuned image reasoning generative models.","pulls":4900000,"pullsDisplay":"4.9M Pulls","tagsCount":9,"capabilities":["vision"],"sizes":["11b","90b"],"updated":"1 year ago","owner":"Meta"},
    {"name":"qwen3-vl","description":"The most powerful vision-language model in the Qwen model family to date.","pulls":4600000,"pullsDisplay":"4.6M Pulls","tagsCount":57,"capabilities":["vision","tools","thinking"],"sizes":["2b","4b","8b","30b","32b","235b"],"updated":"8 months ago","owner":"Alibaba Cloud"},
    {"name":"qwen3.5","description":"Qwen 3.5 is a family of open-source multimodal models that delivers exceptional utility and performance.","pulls":15800000,"pullsDisplay":"15.8M Pulls","tagsCount":64,"capabilities":["vision","tools","thinking","cloud"],"sizes":["0.8b","2b","4b","9b","27b","35b","122b"],"updated":"2 months ago","owner":"Alibaba Cloud"},
    {"name":"llama2","description":"Llama 2 is a collection of foundation language models ranging from 7B to 70B parameters.","pulls":7300000,"pullsDisplay":"7.3M Pulls","tagsCount":102,"capabilities":[],"sizes":["7b","13b","70b"],"updated":"2 years ago","owner":"Meta"},
    {"name":"llama3.3","description":"New state of the art 70B model offering similar performance compared to the Llama 3.1 405B model.","pulls":4100000,"pullsDisplay":"4.1M Pulls","tagsCount":14,"capabilities":["tools"],"sizes":["70b"],"updated":"1 year ago","owner":"Meta"},
    {"name":"minicpm-v","description":"A series of multimodal LLMs designed for vision-language understanding.","pulls":5300000,"pullsDisplay":"5.3M Pulls","tagsCount":17,"capabilities":["vision"],"sizes":["8b"],"updated":"1 year ago","owner":"MiniCPM"},
    {"name":"dolphin3","description":"Dolphin 3.0 Llama 3.1 8B is the next generation of the Dolphin series of instruct-tuned models.","pulls":3900000,"pullsDisplay":"3.9M Pulls","tagsCount":5,"capabilities":[],"sizes":["8b"],"updated":"1 year ago","owner":"Eric Hartford"},
    {"name":"deepseek-v3","description":"A strong MoE language model with 671B total parameters with 37B activated for each token.","pulls":3800000,"pullsDisplay":"3.8M Pulls","tagsCount":5,"capabilities":[],"sizes":["37b"],"updated":"1 year ago","owner":"DeepSeek"},
    {"name":"qwen2","description":"Qwen2 is a new series of large language models from Alibaba group","pulls":6000000,"pullsDisplay":"6M Pulls","tagsCount":97,"capabilities":["tools"],"sizes":["0.5b","1.5b","7b","72b"],"updated":"1 year ago","owner":"Alibaba Cloud"},
    {"name":"qwen3.6","description":"Qwen3.6 delivers substantial upgrades in agentic coding and thinking preservation.","pulls":4300000,"pullsDisplay":"4.3M Pulls","tagsCount":30,"capabilities":["vision","tools","thinking"],"sizes":["27b","35b"],"updated":"1 month ago","owner":"Alibaba Cloud"},
    {"name":"mistral-nemo","description":"A state-of-the-art 12B model with 128k context length, built by Mistral AI in collaboration with NVIDIA.","pulls":5500000,"pullsDisplay":"5.5M Pulls","tagsCount":17,"capabilities":["tools"],"sizes":["12b"],"updated":"12 months ago","owner":"Mistral AI"},
    {"name":"bge-m3","description":"BGE-M3 is a new model from BAAI distinguished for its versatility in Multi-Functionality, Multi-Linguality, and Multi-Granularity.","pulls":5300000,"pullsDisplay":"5.3M Pulls","tagsCount":3,"capabilities":["embedding"],"sizes":[],"updated":"1 year ago","owner":"BAAI"},
    {"name":"smollm2","description":"SmolLM2 is a family of compact language models available in three sizes: 135M, 360M, and 1.7B parameters.","pulls":3600000,"pullsDisplay":"3.6M Pulls","tagsCount":49,"capabilities":["tools"],"sizes":["1.7b"],"updated":"1 year ago","owner":"HuggingFace"},
    {"name":"deepseek-coder","description":"DeepSeek Coder is a capable coding model trained on two trillion code and natural language tokens.","pulls":4400000,"pullsDisplay":"4.4M Pulls","tagsCount":102,"capabilities":[],"sizes":["1.3b","6.7b","33b"],"updated":"2 years ago","owner":"DeepSeek"},
    {"name":"tinyllama","description":"The TinyLlama project is an open endeavor to train a compact 1.1B Llama model on 3 trillion tokens.","pulls":5300000,"pullsDisplay":"5.3M Pulls","tagsCount":36,"capabilities":[],"sizes":["1.1b"],"updated":"2 years ago","owner":"Meta"},
    {"name":"qwen2.5vl","description":"Flagship vision-language model of Qwen and also a significant leap from the previous Qwen2-VL.","pulls":3300000,"pullsDisplay":"3.3M Pulls","tagsCount":17,"capabilities":["vision"],"sizes":["3b","7b","32b","72b"],"updated":"1 year ago","owner":"Alibaba Cloud"},
    {"name":"granite3.1-moe","description":"The IBM Granite 1B and 3B models are long-context MoE Granite models.","pulls":3000000,"pullsDisplay":"3M Pulls","tagsCount":33,"capabilities":["tools"],"sizes":["1b","3b"],"updated":"1 year ago","owner":"IBM"},
    {"name":"all-minilm","description":"Embedding models on very large sentence level datasets.","pulls":3300000,"pullsDisplay":"3.3M Pulls","tagsCount":10,"capabilities":["embedding"],"sizes":[],"updated":"2 years ago","owner":"Sentence Transformers"},
    {"name":"starcoder2","description":"StarCoder2 is the next generation of transparently trained open code LLMs.","pulls":2900000,"pullsDisplay":"2.9M Pulls","tagsCount":67,"capabilities":[],"sizes":["3b","7b","15b"],"updated":"1 year ago","owner":"BigCode"},
    {"name":"codegemma","description":"CodeGemma is a collection of powerful, lightweight models for coding tasks.","pulls":3100000,"pullsDisplay":"3.1M Pulls","tagsCount":85,"capabilities":[],"sizes":["2b","7b"],"updated":"2 years ago","owner":"Google DeepMind"},
    {"name":"snowflake-arctic-embed","description":"A suite of text embedding models by Snowflake, optimized for performance.","pulls":3100000,"pullsDisplay":"3.1M Pulls","tagsCount":16,"capabilities":["embedding"],"sizes":[],"updated":"2 years ago","owner":"Snowflake"},
    {"name":"falcon3","description":"A family of efficient AI models under 10B parameters performant in science, math, and coding.","pulls":2600000,"pullsDisplay":"2.6M Pulls","tagsCount":17,"capabilities":[],"sizes":["1b","3b","7b","10b"],"updated":"1 year ago","owner":"TII"},
    {"name":"phi4-reasoning","description":"Phi 4 reasoning and reasoning plus are 14-billion parameter open-weight reasoning models.","pulls":1700000,"pullsDisplay":"1.7M Pulls","tagsCount":9,"capabilities":[],"sizes":["14b"],"updated":"1 year ago","owner":"Microsoft"},
    {"name":"qwq","description":"QwQ is the reasoning model of the Qwen series.","pulls":2300000,"pullsDisplay":"2.3M Pulls","tagsCount":8,"capabilities":["tools"],"sizes":["32b"],"updated":"1 year ago","owner":"Alibaba Cloud"},
    {"name":"cogito","description":"Cogito v1 Preview is a family of hybrid reasoning models by Deep Cogito.","pulls":2100000,"pullsDisplay":"2.1M Pulls","tagsCount":20,"capabilities":["tools"],"sizes":["3b","8b","14b","32b","70b"],"updated":"1 year ago","owner":"DeepCogito"},
    {"name":"llama4","description":"Meta's latest collection of multimodal models.","pulls":1800000,"pullsDisplay":"1.8M Pulls","tagsCount":11,"capabilities":["vision","tools"],"sizes":[],"updated":"1 year ago","owner":"Meta"},
    {"name":"mistral-small","description":"Mistral Small 3 sets a new benchmark in the small LLM category below 70B.","pulls":3100000,"pullsDisplay":"3.1M Pulls","tagsCount":21,"capabilities":["tools"],"sizes":["24b"],"updated":"1 year ago","owner":"Mistral AI"},
    {"name":"granite4","description":"Granite 4 features improved instruction following and tool-calling capabilities.","pulls":1300000,"pullsDisplay":"1.3M Pulls","tagsCount":17,"capabilities":["tools"],"sizes":["1b","3b"],"updated":"8 months ago","owner":"IBM"},
    {"name":"olmo2","description":"OLMo 2 is a new family of 7B and 13B models trained on up to 5T tokens.","pulls":3700000,"pullsDisplay":"3.7M Pulls","tagsCount":9,"capabilities":[],"sizes":["7b","13b"],"updated":"1 year ago","owner":"Allen AI"},
    {"name":"command-r","description":"Command R is a Large Language Model optimized for conversational interaction and long context tasks.","pulls":1500000,"pullsDisplay":"1.5M Pulls","tagsCount":32,"capabilities":["tools"],"sizes":["35b"],"updated":"1 year ago","owner":"Cohere"},
    {"name":"mixtral","description":"A set of Mixture of Experts (MoE) model with open weights by Mistral AI.","pulls":2700000,"pullsDisplay":"2.7M Pulls","tagsCount":70,"capabilities":["tools"],"sizes":[],"updated":"1 year ago","owner":"Mistral AI"},
    {"name":"deepseek-coder-v2","description":"An open-source MoE code language model comparable to GPT4-Turbo in code-specific tasks.","pulls":2800000,"pullsDisplay":"2.8M Pulls","tagsCount":64,"capabilities":[],"sizes":["16b","236b"],"updated":"1 year ago","owner":"DeepSeek"},
    {"name":"dolphin-llama3","description":"Dolphin 2.9 is a new model with 8B and 70B sizes by Eric Hartford based on Llama 3.","pulls":2000000,"pullsDisplay":"2M Pulls","tagsCount":53,"capabilities":[],"sizes":["8b","70b"],"updated":"2 years ago","owner":"Eric Hartford"},
    {"name":"hermes3","description":"Hermes 3 is the latest version of the flagship Hermes series of LLMs by Nous Research","pulls":1500000,"pullsDisplay":"1.5M Pulls","tagsCount":65,"capabilities":["tools"],"sizes":["3b","8b","70b","405b"],"updated":"1 year ago","owner":"Nous Research"},
    {"name":"yi","description":"Yi 1.5 is a high-performing, bilingual language model.","pulls":1300000,"pullsDisplay":"1.3M Pulls","tagsCount":174,"capabilities":[],"sizes":["6b","9b","34b"],"updated":"2 years ago","owner":"01.AI"},
    {"name":"openthinker","description":"A fully open-source family of reasoning models built using a dataset derived by distilling DeepSeek-R1.","pulls":1100000,"pullsDisplay":"1.1M Pulls","tagsCount":15,"capabilities":[],"sizes":["7b","32b"],"updated":"1 year ago","owner":"Nous Research"},
    {"name":"granite-code","description":"A family of open foundation models by IBM for Code Intelligence","pulls":1400000,"pullsDisplay":"1.4M Pulls","tagsCount":162,"capabilities":[],"sizes":["3b","8b","20b","34b"],"updated":"1 year ago","owner":"IBM"},
    {"name":"command-r-plus","description":"Command R+ is a powerful, scalable LLM purpose-built to excel at real-world enterprise use cases.","pulls":779600,"pullsDisplay":"779.6K Pulls","tagsCount":21,"capabilities":["tools"],"sizes":["104b"],"updated":"1 year ago","owner":"Cohere"},
    {"name":"deepscaler","description":"A fine-tuned version of Deepseek-R1-Distilled-Qwen-1.5B that surpasses the performance of OpenAI's o1-preview.","pulls":1300000,"pullsDisplay":"1.3M Pulls","tagsCount":5,"capabilities":[],"sizes":["1.5b"],"updated":"1 year ago","owner":"DeepSeek"},
    {"name":"moondream","description":"moondream2 is a small vision language model designed to run efficiently on edge devices.","pulls":1400000,"pullsDisplay":"1.4M Pulls","tagsCount":18,"capabilities":["vision"],"sizes":["1.8b"],"updated":"2 years ago","owner":"Moondream"},
    {"name":"mistral-large","description":"Mistral Large 2 is Mistral's new flagship model that is significantly more capable in code generation, mathematics, and reasoning.","pulls":1200000,"pullsDisplay":"1.2M Pulls","tagsCount":32,"capabilities":["tools"],"sizes":["123b"],"updated":"1 year ago","owner":"Mistral AI"},
    {"name":"sqlcoder","description":"SQLCoder is a code completion model fined-tuned on StarCoder for SQL generation tasks","pulls":1300000,"pullsDisplay":"1.3M Pulls","tagsCount":48,"capabilities":[],"sizes":["7b","15b"],"updated":"2 years ago","owner":"Defog"},
    {"name":"openchat","description":"A family of open-source models trained on a wide variety of data, surpassing ChatGPT on various benchmarks.","pulls":1200000,"pullsDisplay":"1.2M Pulls","tagsCount":50,"capabilities":[],"sizes":["7b"],"updated":"2 years ago","owner":"Nous Research"},
    {"name":"zephyr","description":"Zephyr is a series of fine-tuned versions of the Mistral and Mixtral models that are trained to act as helpful assistants.","pulls":1200000,"pullsDisplay":"1.2M Pulls","tagsCount":40,"capabilities":[],"sizes":["7b","141b"],"updated":"2 years ago","owner":"HuggingFace"},
    {"name":"deepseek-llm","description":"An advanced language model crafted with 2 trillion bilingual tokens.","pulls":1100000,"pullsDisplay":"1.1M Pulls","tagsCount":64,"capabilities":[],"sizes":["7b","67b"],"updated":"2 years ago","owner":"DeepSeek"},
    {"name":"deepseek-v2","description":"A strong, economical, and efficient Mixture-of-Experts language model.","pulls":1100000,"pullsDisplay":"1.1M Pulls","tagsCount":34,"capabilities":[],"sizes":["16b","236b"],"updated":"2 years ago","owner":"DeepSeek"},
    {"name":"snowflake-arctic-embed2","description":"Snowflake's frontier embedding model. Arctic Embed 2.0 adds multilingual support.","pulls":426200,"pullsDisplay":"426.2K Pulls","tagsCount":3,"capabilities":["embedding"],"sizes":[],"updated":"1 year ago","owner":"Snowflake"},
    {"name":"dbrx","description":"DBRX is an open, general-purpose LLM created by Databricks.","pulls":314900,"pullsDisplay":"314.9K Pulls","tagsCount":7,"capabilities":[],"sizes":["132b"],"updated":"2 years ago","owner":"Databricks"},
    {"name":"reflection","description":"A high-performing model trained with Reflection-tuning that teaches a LLM to detect mistakes in its reasoning.","pulls":601500,"pullsDisplay":"601.5K Pulls","tagsCount":17,"capabilities":[],"sizes":["70b"],"updated":"1 year ago","owner":"Reflection AI"},
    {"name":"tulu3","description":"Tülu 3 is a leading instruction following model family, offering fully open-source data, code, and recipes by Allen AI.","pulls":372600,"pullsDisplay":"372.6K Pulls","tagsCount":9,"capabilities":[],"sizes":["8b","70b"],"updated":"1 year ago","owner":"Allen AI"},
    {"name":"command-a","description":"111 billion parameter model optimized for demanding enterprises that require fast, secure, and high-quality AI","pulls":221300,"pullsDisplay":"221.3K Pulls","tagsCount":5,"capabilities":["tools"],"sizes":["111b"],"updated":"1 year ago","owner":"Cohere"},
    {"name":"alfred","description":"A robust conversational model designed to be used for both chat and instruct use cases.","pulls":233800,"pullsDisplay":"233.8K Pulls","tagsCount":7,"capabilities":[],"sizes":["40b"],"updated":"2 years ago","owner":"Alfred"},
]

with open(output_path, 'w') as f:
    json.dump(models, f, indent=2)

print(f"Saved {len(models)} models to {output_path}")
print(f"Unique owners: {len(set(m['owner'] for m in models))}")
top = sorted(set(m['owner'] for m in models), key=lambda o: sum(m['pulls'] for m in models if m['owner']==o), reverse=True)
for o in top[:10]:
    count = sum(1 for m in models if m['owner']==o)
    total_pulls = sum(m['pulls'] for m in models if m['owner']==o)
    print(f"  {o}: {count} models, {total_pulls/1e6:.1f}M total pulls")